### ISSUE TITLE
Overlay blocking end turn button

### ISSUE THREAD

**Issue by amosbastian** [miniature-tiger/archipelago#54]
#### What happens and how to reproduce
Clicking on e.g. a ship brings up an overlay at the bottom that covers the end turn button partially.

* Browser version: Chrome 66
* Operating system: Ubuntu 16.04 LTS

#### Recording of the bug
![archipelago](https://user-images.githubusercontent.com/9199433/40182289-5f7c0bb2-59eb-11e8-9d61-fedd6c91424e.gif)

**Comment by miniature-tiger** [comment]
This should now be fixed for all elements after the last commit. 
Thanks to amosbaastian for raising this one!
